version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - pg
    environment:
        - DATABASE_URL=postgresql://postgres:postgres@pg:5432/postgres
    stop_signal: SIGINT
    stop_grace_period: 10s
    cpu_count: 32
    mem_reservation: "32GB"

  pg:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432"
    restart: unless-stopped
